"""render/markdown.py — shared Markdown + vault helpers.

Deliberately dependency-free (no PyYAML): a small, controlled frontmatter
emitter for the scalar/list values we actually write. Atomic writes only —
write-temp-then-os.replace — so Obsidian never sees a half-written note
(and a sync-backed vault never indexes a torn file).
"""
from __future__ import annotations

import os
from pathlib import Path

BANNER = (
    "> [!warning] AUTO-GENERATED — do not edit.\n"
    "> Regenerated by quant-tracker (`track report`). Edits will be overwritten."
)

TRACKER_SUBDIR = "90 Tracker"


# ── Vault path resolution ────────────────────────────────────────────────────

# Mirrors doctor.CANONICAL_VAULT — kept here so render/ has no import cycle with
# doctor.py (which lives at repo root, not on the package path under all runs).
_CANONICAL_VAULT = (
    "/Users/user/Library/CloudStorage/"
    "GoogleDrive-user@example.com/My Drive 2/"
    "02_Knowledge/Obsidian/TJ_Vault/Investment_AI"
)


def vault_root() -> Path:
    """The Investment_AI vault dir. VAULT_PATH env overrides the canonical mount."""
    return Path(os.getenv("VAULT_PATH", _CANONICAL_VAULT))


def tracker_dir() -> Path:
    """The ``90 Tracker/`` folder where all generated notes live."""
    return vault_root() / TRACKER_SUBDIR


# ── Frontmatter ──────────────────────────────────────────────────────────────

def _scalar(v: object) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    s = str(v)
    # Quote when YAML could misread it (specials, leading/trailing space, etc.).
    if s == "" or s[0] in "@#&*!|>%`\"'{}[],:?-" or s != s.strip() or ": " in s:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def frontmatter(fields: dict) -> str:
    """Emit a YAML frontmatter block. Values: scalar or list-of-scalars."""
    lines = ["---"]
    for key, val in fields.items():
        if isinstance(val, (list, tuple)):
            if not val:
                lines.append(f"{key}: []")
            else:
                lines.append(f"{key}:")
                lines.extend(f"  - {_scalar(x)}" for x in val)
        else:
            lines.append(f"{key}: {_scalar(val)}")
    lines.append("---")
    return "\n".join(lines)


def document(fields: dict, body: str) -> str:
    """Assemble a full note: frontmatter + AUTO-GENERATED banner + body."""
    return f"{frontmatter(fields)}\n\n{BANNER}\n\n{body.rstrip()}\n"


# ── Markdown tables ──────────────────────────────────────────────────────────

def table(headers: list[str], rows: list[list[object]]) -> str:
    """Render a GitHub-flavored Markdown table. Empty rows → an italic note."""
    if not rows:
        return "_No rows._"
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = "\n".join(
        "| " + " | ".join("" if c is None else str(c) for c in row) + " |"
        for row in rows
    )
    return f"{head}\n{sep}\n{body}"


def pct(x: float | None, digits: int = 1) -> str:
    return "—" if x is None else f"{x * 100:.{digits}f}%"


def money(x: float | None, digits: int = 2) -> str:
    return "—" if x is None else f"${x:,.{digits}f}"


def num(x: float | None, digits: int = 4) -> str:
    return "—" if x is None else f"{x:.{digits}f}"


# ── Atomic write ─────────────────────────────────────────────────────────────

def atomic_write(path: Path, content: str) -> Path:
    """Write content to ``path`` atomically (temp in same dir, then replace)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)  # atomic on same filesystem
    return path
