"""render/slides.py — auto-generated investment-review slide deck (Insight U20).

Pure: data dicts → a Slides-Extended / advanced-slides Markdown deck string.
The deck is FULLY STATIC (computed values, no Dataview queries — advanced-slides
conflicts with Dataview). Degrades gracefully: without the plugin it's still
readable Markdown (headings/tables); the ```chart block shows as a code block.

Slide syntax: a leading YAML frontmatter block configures the deck; `---` on its
own line (blank lines around) separates horizontal slides. Targets the maintained
"Slides Extended" fork (the original advanced-slides is discontinued).
"""
from __future__ import annotations

from render.markdown import equity_chart, num, pct, table
from render.notes import _scorecard_verdict

# Horizontal slide break (blank lines around the rule, per the slide syntax).
_SEP = "\n\n---\n\n"


def review_deck(regime: dict, top_picks: list[dict], scorecard: dict,
                snapshots: list[dict], backtest: dict | None = None,
                as_of: str | None = None) -> str:
    """Assemble the weekly-review slide deck. All inputs may be empty/sparse."""
    regime = regime or {}
    label = str(regime.get("label", "unknown")).upper()
    conf = float(regime.get("confidence", 0) or 0)
    day = (as_of or "")[:10]

    slides: list[str] = []

    # 1) Title (speaker note carries the auto-generated marker).
    slides.append(
        f"# Quant Tracker\n## Weekly Investment Review\n\n{day}\n\n"
        "_Paper-trading research — not financial advice._\n\n"
        "note:\nAuto-generated by quant-tracker (`track review`). Do not hand-edit."
    )

    # 2) Regime.
    slides.append(f"# Market Regime\n\n## {label}\n\nConfidence **{pct(conf)}**")

    # 3) Top picks.
    picks_tbl = table(
        ["Rank", "Ticker", "Sector", "Score"],
        [[s.get("rank"), s.get("ticker"), s.get("sector"),
          num(s.get("composite_score"))] for s in (top_picks or [])],
    )
    slides.append(f"# This Week's Top Picks\n\n{picks_tbl}")

    # 4) Scorecard (is it working?).
    horizons = (scorecard or {}).get("horizons", {})
    verdict, _ = _scorecard_verdict(horizons)
    sc_rows = []
    for lbl, k in (("7 days", "7d"), ("28 days", "28d"), ("84 days", "84d")):
        s = horizons.get(k, {})
        cov = s.get("coverage")
        sc_rows.append([lbl, s.get("n", 0), pct(s.get("hit_rate")),
                        pct(s.get("avg_alpha")),
                        "—" if cov is None else pct(cov, 0)])
    sc_tbl = table(["Horizon", "Picks", "% beat SPY", "Avg edge", "Coverage"], sc_rows)
    slides.append(f"# Are the Picks Working?\n\n{verdict}\n\n{sc_tbl}")

    # 5) Paper performance (equity curve chart).
    slides.append(f"# Paper Performance vs Market\n\n{equity_chart(snapshots or [])}")

    # 6) Backtest (optional — only if a backtest dict is supplied).
    if backtest:
        wf = backtest.get("walk_forward", {}) or {}
        slides.append(
            "# Backtest — Evidence of Skill\n\n"
            f"Top picks beat the average stock in **{pct(wf.get('win_rate'), 0)}** of "
            f"**{wf.get('n_windows', 0)}** historical test windows "
            f"(avg lift **{pct(wf.get('mean_lift'))}**).\n\n"
            "_Measured on history the models partly saw — the live Scorecard is the real test._"
        )

    frontmatter = "---\ntheme: black\ntransition: slide\nenableLinks: true\n---"
    return frontmatter + "\n\n" + _SEP.join(slides) + "\n"


__all__ = ["review_deck"]
